name: run main unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.3.1
        with: 
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare gradlew
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2.5.0
        if: always() 
        with:
          report_paths: '**/build/test-results/test*/TEST-*.xml'
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v2.1.0
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Clean builds
        if: ${{ always() }}
        run: ./gradlew clean
